### ISSUE TITLE
Unable to migrate vault from version 1 -> 2

### ISSUE THREAD

**Issue by ruimgoncalves** [securefolderfs-community/SecureFolderFS#77]
### Description

After being prompt to upgrade got the following error

```
System.NotSupportedException: Stream does not support writing.
   at System.IO.Stream.ValidateCopyToArguments(Stream destination, Int32 bufferSize)
   at System.IO.FileStream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at SecureFolderFS.Storage.Extensions.StorageExtensions.CopyContentsToAsync(IFile source, IFile destination, CancellationToken cancellationToken)
   at SecureFolderFS.Storage.Extensions.StorageExtensions.CopyContentsToAsync(IFile source, IFile destination, CancellationToken cancellationToken)
   at SecureFolderFS.Storage.Extensions.StorageExtensions.CopyContentsToAsync(IFile source, IFile destination, CancellationToken cancellationToken)
   at SecureFolderFS.Core.Migration.AppModels.V1_V2.MigratorV1_V2.CreateKeystoreBackup(CancellationToken cancellationToken)
   at SecureFolderFS.Core.Migration.AppModels.V1_V2.MigratorV1_V2.MigrateAsync(IDisposable unlockContract, ProgressModel progress, CancellationToken cancellationToken)
   at SecureFolderFS.Core.Migration.AppModels.V1_V2.MigratorV1_V2.MigrateAsync(IDisposable unlockContract, ProgressModel progress, CancellationToken cancellationToken)
   at SecureFolderFS.Sdk.ViewModels.Views.Overlays.MigrationOverlayViewModel.MigrateAsync(CancellationToken cancellationToken)
```

### To Reproduce

1. Open App
2. Select Vault
3. Enter correct password when prompted
4. Select Migrate

### App Version

0.6.0

### OS Version

Windows 11

### Diagnostic information

![image](https://github.com/user-attachments/assets/9227cb3e-22f6-4c65-b553-f6eba8fdc97f)

**Comment by d2dyno1** [comment]
Thanks for the report! Looking into it :eyes:

**Comment by d2dyno1** [comment]
This has now been fixed in https://github.com/securefolderfs-community/SecureFolderFS/commit/754d10c7ea4cbd8434bc632b7414b8ef97e58661. I'll create a new submission to the Microsoft Store as soon as another one finishes proceeding. This issue will be closed when that happens

**Comment by d2dyno1** [comment]
The update should now be available on the Microsoft Store

**Comment by ruimgoncalves** [comment]
Just confirmed, it's working.

Thanks for the quick fix!
